### ISSUE TITLE
GitHub Actions: Installing dependencies with mamba >0.20.0 fails

### ISSUE THREAD

**Issue by hinerm** [apposed/jgo#69]
Produces the following error report:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/share/miniconda/lib/python3.9/site-packages/conda/exceptions.py", line 10[8](https://github.com/hinerm/jgo/runs/6309610914?check_suite_focus=true#step:5:8)2, in __call__
        return func(*args, **kwargs)
      File "/usr/share/miniconda/lib/python3.[9](https://github.com/hinerm/jgo/runs/6309610914?check_suite_focus=true#step:5:9)/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/share/miniconda/lib/python3.9/site-packages/conda_env/cli/main_update.py", line 126, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/usr/share/miniconda/lib/python3.9/site-packages/mamba/mamba_env.py", line 53, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/usr/share/miniconda/lib/python3.9/site-packages/mamba/utils.py", line 122, in load_channels
        index = get_index(
      File "/usr/share/miniconda/lib/python3.9/site-packages/mamba/utils.py", line [10](https://github.com/hinerm/jgo/runs/6309610914?check_suite_focus=true#step:5:10)3, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Operation not permitted: '/usr/share/miniconda/pkgs/cache/3e39a7aa.json'

`$ /usr/share/miniconda/bin/mamba update --file environment-test.yml --name base`

  environment variables:
                 CIO_TEST=<not set>
                    CONDA=/usr/share/miniconda
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/usr/share/miniconda
           CURL_CA_BUNDLE=<not set>
      DEPLOYMENT_BASEPATH=/opt/runner
        GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
              GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_cb8069e7-8d39-4
                          61e-8f9c-aa9c0a9dc8aa
                     PATH=/usr/share/miniconda/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbre
                          w/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.
                          cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/b
                          in:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin
                          :/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
        SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
            SSL_CERT_FILE=<not set>
               SWIFT_PATH=/usr/share/swift/usr/bin

     active environment : None
       user config file : /home/runner/.condarc
 populated config files : 
          conda version : 4.[12](https://github.com/hinerm/jgo/runs/6309610914?check_suite_focus=true#step:5:12).0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.[13](https://github.com/hinerm/jgo/runs/6309610914?check_suite_focus=true#step:5:13).0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/share/miniconda  (writable)
      conda av data dir : /usr/share/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/share/miniconda/pkgs
                          /home/runner/.conda/pkgs
       envs directories : /usr/share/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.7 Linux/5.13.0-1022-azure ubuntu/[20](https://github.com/hinerm/jgo/runs/6309610914?check_suite_focus=true#step:5:20).04.4 glibc/2.31
                UID:GID : 1001:1[21](https://github.com/hinerm/jgo/runs/6309610914?check_suite_focus=true#step:5:21)
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Error: Process completed with exit code 1.
```

**Comment by hinerm** [comment]
> Can't replicate on my machine with:

Ah sorry, it's only happening in the [GitHub Actions builds](https://github.com/scijava/jgo/runs/6309273888?check_suite_focus=true).
